<?php 
if(!empty($_GET['cat'])){
    if(is_file('_views/'.$_GET['cat'].'_root.php')){
        if(!empty($_GET['view'])){
            if(is_file('_views/'.$_GET['cat'].'/'.$_GET['view'].'.php')){
                include('_views/'.$_GET['cat'].'/'.$_GET['view'].'.php');
            }
            else{
                include('_controllers/404.php');
            }
        }
        else{
            include('_views/'.$_GET['cat'].'_root.php');
        }
    }
    else{
        include('_controllers/404.php');
    }
}
else{
    include('_includes/public.php');
}
?>